sudo: false
language: python
before_script:
  - pip install -r requirements.txt
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov -e TOXENV
